name: flutter_todolist
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  validators: ^2.0.0
  email_validator: ^2.0.1
  shared_preferences: ^2.0.12
  flutter_staggered_grid_view: ^0.4.0
  flutter_local_notifications: ^6.0.0
  timezone: ^0.7.0
  roundcheckbox: ^2.0.4+1
  favicon: ^1.0.15
  flutter_slidable: "^0.6.0"
  new_gradient_app_bar: ^0.2.0
  flutter_svg: ^0.22.0
  sqflite: ^2.0.0+4
  intl: ^0.17.0
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
